default:
	@echo default
kTimesOneTime.out:kTimesOneTime.cc
	g++ kTimesOneTime.cc -o kTimesOneTime.out -g -Wall -O0

binaryTreeMaxPathSum.out:binaryTreeMaxPathSum.cc
	g++ binaryTreeMaxPathSum.cc -o binaryTreeMaxPathSum.out -g -Wall -O0
wordBreak.out:wordBreak.cc
	g++ wordBreak.cc -o wordBreak.out -g -Wall -O0

.PHONY=clean
clean:
	rm *.out -f
